consolidator/config/routes.rb
Consolidator::Application.routes.draw do
  get "welcome/index"

  resources :companies do
    resources :companies
  end
  root 'welcome#index'

  

end

consolidator/app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :company
  has_many :companies
  validates :name, presence: true,
                    length: { minimum: 2 }
end

consolidator/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	def new
		@company = Company.new
	end

	def create

		if params[:company_id]
			@company = Company.find(params[:company_id])
	    	@parent = @company.companies.create(params[:company].permit(:name))
	    	redirect_to company_path(@company)
	    else
	    	@company = Company.new(company_params)

			if @company.save			
				redirect_to @company
			else
				render 'new'
			end
		end		
		
	end

	def show
		@company = Company.find(params[:id])
	end

	def edit
		@company = Company.find(params[:id])
	end

	def update
	  @company = Company.find(params[:id])
	 
	  if @company.update(params[:company].permit(:name))
	    redirect_to @company
	  else
	    render 'edit'
	  end
	end

	def index
		@companies = Company.all
	end
	
	private
	def company_params
		params.require(:company).permit(:name)
	end
end

consolidator/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	redirect_to companies_path
  end
end

consolidator/app/helpers/companies_helper.rb
module CompaniesHelper
end

consolidator/app/views/companies/_form.html.erb
<%= form_for @company, url: companies_path do |f| %>

<% if @company.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@company.errors.count, "error") %> prohibited
      this company from being saved:</h2>
    <ul>
    <% @company.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
 <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <table>     
      <tr>
        <td></td>
        <td>Black</td>
        <td>White</td>
      </tr>
      <tr>
        <td>Males</td>
        <td><%= f.text_field :black_male %></td>
        <td><%= f.text_field :white_male %></td>
      </tr>
      <tr>
        <td>Females</td>
        <td><%= f.text_field :black_female %></td>
        <td><%= f.text_field :white_female %></td>       
      </tr>     
  </table>
  
  <p>
    <%= f.submit %>
  </p>

<% end %>

consolidator/app/views/companies/edit.html.erb
<h1>Editing Company</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', companies_path %>

consolidator/app/views/companies/index.html.erb
<h1>All Companies</h1>

<% if @companies.length > 0 %>
	<p>
	Below is a list of companies in Consolidator. Select a company
	to view its subsidiaries and demographics.
	</p> 

	<table> 
	  <% @companies.each do |company| %>
	    <tr>
	      <td><%= link_to company.name, company_path(company) %></td>
	      <% if company.companies.length > 0 %>
	      	<td>(<%= pluralize(company.companies.length, "subsidiary") %>)</td>
	      <% end %>
	    </tr>
	  <% end %>
	</table>
<% else %>
	<p>
	No companies available.
	</p>
<% end %>

<p>
  <%= link_to 'Add Company', new_company_path %>
</p>

consolidator/app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

consolidator/app/views/companies/show.html.erb
<p>
  <%= link_to 'All Companies', companies_path %> > <%= @company.name%>
</p>

<% if @company.companies.length > 0 %>
	<p>
  		<h2><%= @company.name %>'s consolidated demographics</h2>
	</p>

	<table>     
      <tr>
        <td></td>
        <td>Black</td>
        <td>White</td>
      </tr>
      <tr>
        <td>Males</td>
        <td><%= @company.black_male %></td>
        <td><%= @company.white_male %></td>
      </tr>
      <tr>
        <td>Females</td>
        <td><%= @company.black_female %></td>
        <td><%= @company.white_female %></td>       
      </tr>     
  </table>

	<p>
	  Immediate Subsidiaries
	</p>
	<table> 
	  <% @company.companies.each do |company| %>
	    <tr>
	      <td><%= link_to company.name, company_path(company) %></td>
	    </tr>
	  <% end %>
	</table>
<% else %>
	<p>
	  <h2><%= @company.name %>'s demographics</h2>
	</p>

	<table>     
      <tr>
        <td></td>
        <td>Black</td>
        <td>White</td>
      </tr>
      <tr>
        <td>Males</td>
        <td><%= @company.black_male %></td>
        <td><%= @company.white_male %></td>
      </tr>
      <tr>
        <td>Females</td>
        <td><%= @company.black_female %></td>
        <td><%= @company.white_female %></td>       
      </tr>     
  	</table>

	<p>No immediate subsidiaries.</p>
<% end %>

<%= form_for([@company, @company.companies.build]) do |f| %>
  	<table> 	  
	    <tr>
	      <td><%= f.text_area :name %></td>
	      <td><%= f.hidden_field :id %></td>
	    </tr>
	    <tr>
	      <td><%= f.submit 'Add Immediate Subsidiary' %></td>
	      <td><%= link_to 'Save Inclusion Settings', edit_company_path(@company) %></td>
		</tr>	  
	</table>
<% end %>

consolidator/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Consolidator</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

consolidator/app/views/welcome/index.html.erb
<h1>All Companies</h1>
<p>Find me in app/views/welcome/index.html.erb</p>